nelmio_api_doc:

    documentation:
        info:
            title: GeMargement
            description: Créer une application d'émargement pour les élèves en utilisant une stack technologique moderne et des outils de gestion de projet collaboratifs. Ce projet s'inscrit dans le cadre du BTS SIO SLAM (session 2024/2025) à l'établissement GEFOR.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            
