<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCXHGQuF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCXHGQuF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCXHGQuF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCXHGQuF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCXHGQuF\App_KernelDevDebugContainer([
    'container.build_hash' => 'CXHGQuF',
    'container.build_id' => 'b90d039d',
    'container.build_time' => 1742567922,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCXHGQuF');
